meta_product_name: "Wear"
meta_title: "Wear : find the greenest outfit everywhere"
meta_description: "Relevant description"
meta_image: "favicon.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
